### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter' when starting serena-mcp-server on macOS with Homebrew Python 3.11

### ISSUE THREAD

**Issue by uijin** [oraios/serena#58]
**Environment:**

- Operating System: macOS 15.4
- Python Version: 3.11.12 (installed via Homebrew)
- Virtual Environment Tool: `uv`
- Project Version: Tested on commit `8c9fd74` (latest main as of 2025-04-10 in the provided history)

**Steps to Reproduce:**

1. Set up the project environment using `uv` (or potentially other environment managers) with Python 3.11.12 installed via Homebrew on macOS.

2. Attempt to start the MCP server using the command:

   Bash

   ```
   uv run serena-mcp-server
   ```

**Expected Behavior:**

The `serena-mcp-server` should start successfully without errors.

**Actual Behavior:**

The command fails immediately with a `ModuleNotFoundError`, indicating that the `_tkinter` module cannot be found.

```
Traceback (most recent call last):
  File "/Users/uijin/practice/serena/.venv/bin/serena-mcp-server", line 4, in <module>
    from serena.mcp import start_mcp_server
  File "/Users/uijin/practice/serena/src/serena/mcp.py", line 18, in <module>
    from serena.agent import SerenaAgent, Tool
  File "/Users/uijin/practice/serena/src/serena/agent.py", line 26, in <module>
    from serena.gui_log_viewer import GuiLogViewer, GuiLogViewerHandler
  File "/Users/uijin/practice/serena/src/serena/gui_log_viewer.py", line 7, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.12/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Additional Context:**

- The error occurs because `serena.gui_log_viewer` attempts to import `tkinter`.
- Python installations, especially those not bundled with the OS (like Homebrew versions on macOS), may not include Tk support by default or might require separate installation of Tcl/Tk libraries (`brew install tcl-tk`).
- It might be worth considering if `tkinter` (and thus the `GuiLogViewer`) should be an optional dependency for the core server functionality, or if the requirement for Tk support should be explicitly documented in the setup instructions, especially for macOS/Linux users.

**Comment by MischaPanch** [comment]
Since on mac the GUI cannot be started anyway, we definitely should have the import in a try-except block.

Meanwhile, while waiting for the fix, could you pls see if `brew install python-tk` makes the error disappear?

**Comment by MischaPanch** [comment]
Well, fix was easy, I just pushed directly to main. Pls pull and try again :). Fixed in 36f0103fa2f449c.

@opcode81 FYI

**Comment by uijin** [comment]
Thanks, @MischaPanch . I pull the main branch 

* 36f0103 2025-04-14 | Only import Gui things if Gui is enabled (HEAD -> main, origin/main, origin/HEAD) [Michael Panchenko]

and try to launch the MCP server, but still failed due to the `_tkinter` error.

```
√ practice/serena % uv run serena-mcp-server                                                                                                         19:43:23
Using CPython 3.11.12 interpreter at: /opt/homebrew/opt/python@3.11/bin/python3.11
Creating virtual environment at: .venv
Installed 49 packages in 110ms
Traceback (most recent call last):
  File "/Users/uijin/practice/serena/.venv/bin/serena-mcp-server", line 4, in <module>
    from serena.mcp import start_mcp_server
  File "/Users/uijin/practice/serena/src/serena/mcp.py", line 19, in <module>
    from serena.gui_log_viewer import show_fatal_exception
  File "/Users/uijin/practice/serena/src/serena/gui_log_viewer.py", line 7, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.12/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by s5k** [comment]
I was able to resolve the issue by installing python-tk via Homebrew.

**Comment by MischaPanch** [comment]
Right, there is an error handling that always uses tkinter, even if GUI is disabled. So my fix couldn't solve this, sorry for the mistake. 

This seems to be a general problem with uv and macOS.

Did installing with brew not solve this?

You can also try this hack:

https://github.com/astral-sh/uv/issues/7036#issuecomment-2421594826

Pls let me know how it goes.

We will try to circumvent this by using wxPython, seems like tkinter and macOS don't like each other

**Comment by uijin** [comment]
After installing `python-tk` via Homebrew, the issue was resolved.

Thank you both @MischaPanch @s5k
